# ytdl-sub needs a temporary place to download files. Choose that path here
configuration:
  working_directory: 'tmp'

presets:
  soundcloud_with_id3_tags:
    soundcloud:
      download_strategy: "albums_and_singles"
      skip_premiere_tracks: True
    ytdl_options:
      format: 'bestaudio[ext=mp3]'
    output_options:
      output_directory: "/tmp/{sanitized_artist}"
      file_name: "[{album_year}] {sanitized_album}/{track_number_padded} - {sanitized_title}.{ext}"
      thumbnail_name: "[{album_year}] {sanitized_album}/folder.jpg"
      maintain_download_archive: True
    convert_thumbnail:
      to: "jpg"
    music_tags:
      tags:
        artist: "{artist}"
        albumartist: "{artist}"
        title: "{title}"
        album: "{album}"
        track: "{track_number}"
        year: "{album_year}"
        genre: "{genre}"

  yt_music_video:
    # A single YouTube video is our source/download strategy. However, this
    # can be overwritten to download music videos from a "playlist", as we
    # will see in a preset below
    youtube:
      download_strategy: "video"

    # For advanced YTDL users only.
    # It is wise to leave ignoreerrors=True to avoid errors for things
    # like age-restricted videos in case you have not set your cookie.
    ytdl_options:
      ignoreerrors: True

    # For each video downloaded, set the file and thumbnail name here.
    # We set both with {music_video_name}, which is a variable we define in
    # the overrides section further below to represent consistent naming format.
    output_options:
      output_directory: "{music_video_directory}/{sanitized_artist}"
      file_name: "{music_video_name}.{ext}"
      thumbnail_name: "{music_video_name}.jpg"

    # Always convert the video thumbnail to jpg
    # TODO: always convert all thumbnails to jpg in code
    convert_thumbnail:
      to: "jpg"

    # For each video downloaded, add a music video NFO file for it. Populate it
    # with tags that Kodi will read and use to display it in the music or music
    # videos section.
    nfo_tags:
      nfo_name: "{music_video_name}.nfo"
      nfo_root: "musicvideo"
      tags:
        artist: "{artist}"
        title: "{title}"
        album: "Music Videos"
        year: "{upload_year}"

    # Overrides is a section where we can define our own variables, and use them in
    # any other section. We define our music video directory and episode file name
    # here, which gets reused above for the video, thumbnail, and NFO file.
    overrides:
      music_video_directory: "path/to/Music Videos"
      music_video_name: "{sanitized_artist} - {sanitized_title}"

    # It is not always ideal to download all of an artist's music videos.
    # Maybe you only like one song of theirs. We can reuse our preset above
    # to download a single video instead.
    yt_music_video_playlist:
      preset: "yt_music_video"
      youtube:
        download_strategy: "playlist"

      # Setting maintain_download_archive=True is generally a good thing to enable
      # with playlists and channels because it will store previously downloaded
      # video ids to tell YTDL not to re-download them on a successive invocation.
      output_options:
        maintain_download_archive: True

      # Setting break_on_existing=True is also a good thing anytime you are using
      # a download archive, because it will tell the downloader to stop trying
      # to download videos that have already been downloaded.
      ytdl_options:
        break_on_existing: True

  yt_channel:
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"
    ytdl_options:
      ignoreerrors: True
    output_options:
      file_name: "{output_file_name}.{ext}"
      thumbnail_name: "{output_file_name}.jpg"
    convert_thumbnail:
      to: "jpg"
    nfo_tags:
      nfo_name: "{output_file_name}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{upload_year}"
        episode: "{upload_month}{upload_day_padded}"
        plot: "{description}"
        year: "{upload_year}"
        aired: "{upload_date_standardized}"
    output_directory_nfo_tags:
      nfo_name: "tvshow.nfo"
      nfo_root: "tvshow"
      tags:
        title: "{tv_show_name}"
    overrides:
      output_file_name: "Season {upload_year}/s{upload_year}.e{upload_month_padded}{upload_day_padded} - {sanitized_title}"