#!/usr/bin/with-contenv bash

echo "Starting ytdl-sub..."

# copy config
[[ ! -e "$DEFAULT_WORKSPACE/config.yaml" ]] && \
    mkdir -p "$DEFAULT_WORKSPACE" && \
    cp /defaults/config.yaml "$DEFAULT_WORKSPACE/config.yaml"
[[ ! -e "$DEFAULT_WORKSPACE/subscriptions.yaml" ]] && \
    mkdir -p "$DEFAULT_WORKSPACE" && \
    cp /defaults/subscriptions.yaml "$DEFAULT_WORKSPACE/subscriptions.yaml"
[[ ! -d "$DEFAULT_WORKSPACE/examples" ]] && \
    mkdir -p "$DEFAULT_WORKSPACE/examples" && \
    cp -r /defaults/examples/* "$DEFAULT_WORKSPACE/examples"

# always create cron log file
touch "$LOGS_TO_STDOUT"

# permissions
chown -R ${PUID:-abc}:${PGID:-abc} \
    /config

# set up cron
if [ "$CRON_SCHEDULE" != "" ] ; then
    [[ ! -e "$CRON_SCRIPT" ]] && \
    cp /defaults/cron "$CRON_SCRIPT"

    cp /defaults/cron_wrapper "$DEFAULT_WORKSPACE/.cron_wrapper"

    CRON_SCHEDULE_CLEAN="${CRON_SCHEDULE//\"/}"
    CRON_SCHEDULE_CLEAN="${CRON_SCHEDULE_CLEAN//\'/}"

    echo "# min   hour    day     month   weekday command" > /config/crontabs/abc
    echo "$CRON_SCHEDULE_CLEAN   $DEFAULT_WORKSPACE/.cron_wrapper" >> /config/crontabs/abc

    chmod +x "$CRON_SCRIPT"
    chown abc:abc "$CRON_SCRIPT"

    crontab -u abc /config/crontabs/abc
else
  echo "CRON_SCHEDULE not specified, disabling cron."
  echo "# min   hour    day     month   weekday command" > /config/crontabs/abc
fi